C1.a.substring
otakubeam/algo pull request #1
Opened 2020-09-30 10:09 UTC by otakubeam

Найдите все вхождения шаблона в строку. Длина шаблона – p, длина строки – n. Время O(n + p), доп. память – O(p).
p ≤ 30000, n ≤ 300000. 

Использовать один из методов: 
Вариант 1. С помощью префикс-функции;
Вариант 2. С помощью z-функции.

2020-09-30 10:10 UTC, otakubeam commented
https://contest.yandex.ru/contest/19772/run-report/34801223/

2020-09-30 10:22 UTC, TalgatMIPT requested changes

2020-09-30 10:22 UTC, TalgatMIPT commented on Contest_1/A.Substring.cpp
> +        std::cout << elem << " ";
```" "``` -magic number

2020-09-30 10:22 UTC, TalgatMIPT commented on Contest_1/A.Substring.cpp
> +    std::vector<int> z_func_vector = z_func(template_line + "#" + search_line);
magic number

2020-09-30 10:22 UTC, TalgatMIPT commented on Contest_1/A.Substring.cpp
> +            positions.push_back(i - template_line.size() - 1);
По дефолту лучше всегда использовать emplace_back

2020-09-30 10:22 UTC, TalgatMIPT commented on Contest_1/A.Substring.cpp
> +    for (int i = template_line.size() + 1; i < concat_size + 1; i++) {
не логично прибавлять 1 и потом ее отнимать

2020-09-30 10:22 UTC, TalgatMIPT commented on Contest_1/A.Substring.cpp
> +#include <map>
не нужен

2020-09-30 10:22 UTC, TalgatMIPT commented on Contest_1/A.Substring.cpp
> +        zf[i] = std::max(0, std::min(right - i, zf[i - left]));
выдели переменную равной zf[i] потом запиши ее в массив

2020-09-30 10:22 UTC, TalgatMIPT commented on Contest_1/A.Substring.cpp
> +// a fucntion to find all instances of template_line in search_line
напиши лучше документирующий комментарий

2020-09-30 11:56 UTC, otakubeam commented
**retested**: https://contest.yandex.ru/contest/19772/run-report/34969035/

2020-09-30 15:23 UTC, TalgatMIPT commented on Contest_1/A.Substring.cpp
> +std::vector<int> z_func(const std::string& str) {
Странным выглядит коммент на одном методе и отсутствие на другом (который тоже из main доступен). Все было бы ок, если он был бы private, но тут классов нет
Давай напишем документирующий коммент и сюда

2020-09-30 15:25 UTC, TalgatMIPT commented on Contest_1/A.Substring.cpp
> +        int calc_val = std::max(0, std::min(right - i, zf[i - left]));
``` calc_val ``` это не крутое наименование

2020-09-30 15:26 UTC, TalgatMIPT commented
Пиши плиз комментарии, что исправил замечание
Как исправишь новые -  апрувну

2020-10-01 08:34 UTC, otakubeam commented on Contest_1/A.Substring.cpp
> +        int calc_val = std::max(0, std::min(right - i, zf[i - left]));
calc_val = calculated_value = подсчитываемое значение. Суть отражает точно

2020-10-01 08:38 UTC, otakubeam commented on Contest_1/A.Substring.cpp
> +std::vector<int> z_func(const std::string& str) {
Исправил

2020-10-01 08:56 UTC, TalgatMIPT commented on Contest_1/A.Substring.cpp
> +        int calc_val = std::max(0, std::min(right - i, zf[i - left]));
Во-первых использовать сокращения в именах переменных не принято (но на это я пока закрою глаза).
Во-вторых, кажется и так понятно по коду, что ты что-то делаешь с ```calc_val```, и судя по количеству ее изменений считаешь. Для человека, который откроет твой код не понятно будет нафига нужен этот ```calc_val```, ведь имена переменных задаются не исходя что с ними будут делать, а какую логику они несут.
```calc_val``` не несет никакой логики, вообще

2020-10-01 13:24 UTC, otakubeam commented on Contest_1/A.Substring.cpp
> +        int calc_val = std::max(0, std::min(right - i, zf[i - left]));
Так а что делать-то? Как назвать? zf[i] подойдёт?

2020-10-01 15:05 UTC, TalgatMIPT approved these changes

2020-10-01 15:10 UTC, merged