[Оразов Андрей] Contest 1, task B
otakubeam/algo pull request #2
Opened 2020-09-30 10:20 UTC by otakubeam

Строка называется палиндромом, если она одинаково читается как слева направо, так и справа налево. Например, «abba» – палиндром, а «roman» – нет.

Для заданной строки s длины n (1 ≤ n ≤ 105) требуется подсчитать число пар (i, j), 1 ≤ i < j ≤ n, таких что подстрока s[i..j] является палиндромом.

https://contest.yandex.ru/contest/19772/run-report/34700108/

2020-09-30 10:29 UTC, TalgatMIPT requested changes

2020-09-30 10:29 UTC, TalgatMIPT commented on B.Palindrome.cpp
> +// counts the number of palindromes of either odd or even length
док-е комм-ии

2020-09-30 10:29 UTC, TalgatMIPT commented on B.Palindrome.cpp
> +int64 count_odd_or_even(const std::string& str, bool odd) {
odd может меняться в методе?

2020-09-30 10:29 UTC, TalgatMIPT commented on B.Palindrome.cpp
> +
зачем две пустые строки?

2020-09-30 10:29 UTC, TalgatMIPT commented on B.Palindrome.cpp
> +            int expr1 = left_bound + right_bound - i + (odd ? 0 : 1);
``` (odd ? 0 : 1) ``` в inline метод

2020-09-30 10:29 UTC, TalgatMIPT commented on B.Palindrome.cpp
> +#include <numeric>
зачем это?

2020-09-30 11:22 UTC, otakubeam commented on B.Palindrome.cpp
> +#include <numeric>
Для std::accumulate(...), чтобы посчитать сумму

2020-09-30 11:41 UTC, otakubeam commented on B.Palindrome.cpp
> +
Мне так удобнее разделять логические блоки.

2020-09-30 11:42 UTC, otakubeam commented
**retested**: https://contest.yandex.ru/contest/19772/run-report/34968250/

2020-09-30 15:07 UTC, TalgatMIPT commented on B.Palindrome.cpp
> +#include <numeric>
Принял
Пиши плиз, что чтот исправил из комментов, не смотря на состояние "outdated"

2020-09-30 15:11 UTC, TalgatMIPT commented on B.Palindrome.cpp
> +
Давай, пожалуйста, сократим до минимума количество этих пустых двойных строк. Хотя бы в методах.
Если это является особенностью твоего кодстайла, пропиши его плиз в README всего репозитория

Я бы избавился от этой привычки, потому что во всех языках типа C, C++, Java, C#, даже Python - это дурной тон
На будущее пригодится. Ты же пойдешь работать по найму с большой вероятности, там в каждой компании свой кодстайл (обычно +- общепринятые варианты, в которых нет двойных пустых строк). Давай формировать правильные привычки со второго курса

2020-09-30 15:14 UTC, TalgatMIPT commented on B.Palindrome.cpp
> +
Более того, к сожалению, кодстайл - это удобный выбор большинства. Большинство твой фетиш не поймет -  значит и код никто смотреть не будет

Когда ты пересаживаешься на другой кодстайл - это всегда больно, так что не унывай! Давай все таки перепишем без двойных пустых

2020-09-30 15:20 UTC, TalgatMIPT requested changes

2020-09-30 15:20 UTC, TalgatMIPT commented on Contest_1/B.Palindrome.cpp
> +inline int is_odd(const bool odd) {
Методы типа is...() всегда возвращают bool, так принято.
Давай изменим название на: ```modulo_if_odd()```, ```parity()``` что-нибудь в таком духе

2020-09-30 15:20 UTC, TalgatMIPT commented on Contest_1/B.Palindrome.cpp
> +            int64 expr2 = static_cast<int64>(right_bound - i + 1);
Тут и в некоторых местах ниже не соблюден кодстайл по пробелам

2020-09-30 15:20 UTC, TalgatMIPT commented on Contest_1/B.Palindrome.cpp
> +            int expr1 = left_bound + right_bound - i + is_odd(!odd);
```expr1``` и ```expr2``` не лучшие наименования

2020-09-30 15:20 UTC, TalgatMIPT commented on Contest_1/B.Palindrome.cpp
> +    int left_bound = 0, right_bound= -1;
0, -1 - это magic numbers

2020-10-01 08:41 UTC, otakubeam commented on Contest_1/B.Palindrome.cpp
> +            int64 expr2 = static_cast<int64>(right_bound - i + 1);
Не согласен. Я соблюдаю свой кодстайл

2020-10-01 08:41 UTC, otakubeam commented on Contest_1/B.Palindrome.cpp
> +inline int is_odd(const bool odd) {
Есть

2020-10-01 08:43 UTC, otakubeam commented on Contest_1/B.Palindrome.cpp
> +            int expr1 = left_bound + right_bound - i + is_odd(!odd);
Эти переменные введены только для того, чтобы не писать длинную непонятную строку. Особых семантических значений у них нет. Изменю на interm_expr1 и interm_expr2, чтобы это подчеркнуть, тогда

2020-10-01 08:47 UTC, otakubeam commented
**retested**: https://contest.yandex.ru/contest/19772/run-report/34994716/

2020-10-01 08:47 UTC, otakubeam commented on Contest_1/B.Palindrome.cpp
> +    int left_bound = 0, right_bound= -1;
Ввёл константы left_start, right_start

2020-10-01 09:03 UTC, otakubeam commented on B.Palindrome.cpp
> +
Не согласен. В python как раз методы разделяются двойными пустыми. 
Я прочитал несколько кодстайлов и в них нет упоминания пустых строк:
https://suckless.org/coding_style/
https://www.kernel.org/doc/Documentation/process/coding-style.rst
http://doc.cat-v.org/bell_labs/pikestyle
https://man.openbsd.org/style

Тем более моим соседям с ИВТ Дединский говорил разделять блоки пустыми линиями, потому что так легче читать. Я с этим согласен

2020-10-01 09:06 UTC, TalgatMIPT requested changes

2020-10-01 09:06 UTC, TalgatMIPT commented on Contest_1/B.Palindrome.cpp
> +            int expr1 = left_bound + right_bound - i + is_odd(!odd);
А это не позиция симметричная ```i```? Как минимум такую семантику можно разглядеть

2020-10-01 09:06 UTC, TalgatMIPT commented on Contest_1/B.Palindrome.cpp
> +                str[i+palindrome_count] == str[position_left]) {
```i+palindrome_count``` Отсутствие пробелов вокруг плюса - это тоже твой кодстайл?

2020-10-01 09:09 UTC, TalgatMIPT commented on Contest_1/B.Palindrome.cpp
> +    const int left_start = 0, right_start = -1;
давай константы (в первую очередь относится к статическим) писать всегда капсом. Например, будет ```const int LEFT_START = 0```

2020-10-01 10:40 UTC, TalgatMIPT commented on B.Palindrome.cpp
> +
Ок, про питон я возможно погорячился
Давай пройдемся по ссылкам, которые ты прикрепил:
1) Это выглядит как не гайдлайн к кодстайлу, а просто микро советы (см. коммент 3 4)
2) Кодстайл ядра линукса специфичен, и поверь, некоторые странности оправданы в ядре линухов. Но по прежнему там запрещены двойные пустые строки. У меня есть хороший друг, который активно ковырял ядро линухов. Я спросил у него - сказал запрещено.
Более того, а давай взглянем на код ядра линухов, он жеж открыт. Вот первый попавшийся файл https://github.com/torvalds/linux/blob/master/kernel/audit.c
Найдешь там две пустые строки - сообщи

3-4) Как это может быть полным гайдлайном по кодстайлу, если он занимает 6 страниц?

Нормальный гайдлайн (полный) должен выглядеть так:
Гугловский) https://google.github.io/styleguide/cppguide.html
Яндекс) https://github.com/yandex/CMICOT/blob/master/CPP_STYLE_GUIDE.md
Мозила) https://firefox-source-docs.mozilla.org/code-quality/coding-style/coding_style_cpp.html

Ты взял очень маленькие гайдлайны каких-то ноунеймов и сказал, что явно не запрещаются двойные пустые строки - не кажется ли тебе это странным?

П.С. товарищ по linux kernel сказал, что если уж так сильно что то хотят отделить в ядре линухов используют ``` //////////////// ```
Но мы не пишем классы на 1000 строк чтобы отделять такими комментариями что-то, поэтому, если ты это тоже будешь использовать - буду запрещать

Аргумент про Дединского
1) Он в индустрии работает сейчас или он только преподаватель?
2) Соседи могли его не так понять? Не так сообщить?
3) Наверное так легче читать Дединскому, которому явно 40+ (без обид), но не остальным

2020-10-01 10:45 UTC, TalgatMIPT commented on B.Palindrome.cpp
> +
И кстати, ты не привел ни один гайдлайн, который обязывает писать двойные пустые строки. А судя по тому, какие ты непопулярные привел, таких нет

2020-10-01 10:48 UTC, TalgatMIPT commented on B.Palindrome.cpp
> +
В прошлом году ассистент очень жестко гонял по кодстайлу, регламентируя использовать **только** яндексовский. В этом году я разрешил небольшие вольности, похоже, зря...

2020-10-01 10:50 UTC, TalgatMIPT commented on B.Palindrome.cpp
> +
А кстати, в следующем семестре у тебя будет курс конкурентных вычислений, на котором будет свой чекер кодстайла. Ты тупо сдать задачу не сможешь, если пробела одного не будет.
Чекеру и преподам ты тоже будешь рассказывать про свой кодстайл и игнорировать аргументы?

2020-10-01 13:25 UTC, otakubeam commented on Contest_1/B.Palindrome.cpp
> +                str[i+palindrome_count] == str[position_left]) {
Да, то, что внутри [], пишется без пробелов

2020-10-01 13:27 UTC, otakubeam commented on Contest_1/B.Palindrome.cpp
> +            int expr1 = left_bound + right_bound - i + is_odd(!odd);
Что значит симметричная i? Не понимаю

2020-10-01 14:00 UTC, otakubeam commented on B.Palindrome.cpp
> +
Я привёл первые, которые пришли на ум. suckless - это команда энтузиастов, которые пишут простые и понятные программы, заменяющие огромные и сложноподдерживаемые старые программы (т.е. должны писать красиво) Они довольно известны, если вы их не знаете, то не надо бросаться словами "нонеймы". Называть "нонеймами" разработчиков линукса, openbsd и сотрудников bell labs (место, где создали C и unix) - тоже очень странно. Для меня они имеют больший авторитет, чем google и яндекс.

Гайдлайн не может **обязывать** писать двойные строки, так как это сложно алгоритмизировать (программист должен опираться на свою логику). Кстати, вы же и сами так пишете: https://github.com/TalgatMIPT/MIPT_Programming/blob/master/4%20term/CAOS/task1_str/main.c

Дединский работает в акронисе. Если честно, вся эта дискуссия кажется излишней и больше похожа на придирку. Я ведь так пишу, чтобы было **удобнее** читать, а не наоборот. И как там пишут гигантские корпорации меня не очень интересует. Когда будет автоматический чекер, а не живой человек, который умеет слушать аргументы, мне придётся писать так, как им хочется. Ничего не поделаешь. Или когда я буду работать в компании, где важно, чтобы разные люди писали более-менее одинаково. Здесь же такой необходимости нет.

**Дайте мне пожалуйста писать две пустые строки подряд!**

2020-10-01 14:17 UTC, TalgatMIPT commented on B.Palindrome.cpp
> +
Ок, согласен с тем, что ты написал
Пиши, как удобно. Только, выпиши, пожалуйста, в какой-нибудь файл основные моменты по твоему стилю, чтобы я не тыкал пальцем и не спрашивал почему так. Делай это, естественно, не в рамках этого ПР

2020-10-01 14:21 UTC, TalgatMIPT commented on Contest_1/B.Palindrome.cpp
> +            int expr1 = left_bound + right_bound - i + is_odd(!odd);
Мы же палиндромы рассматриваем. Если позиция для ```i``` - справа от центра палиндрома, то зеркальная будет получаться как ```r+l-i + (1/0)```, так?

2020-10-01 14:25 UTC, TalgatMIPT commented on B.Palindrome.cpp
> +
Если что я про разрабов ядра отдельно разгонял в сообщении :)

2020-10-01 14:26 UTC, otakubeam commented on Contest_1/B.Palindrome.cpp
> +    const int left_start = 0, right_start = -1;
Есть

2020-10-01 14:27 UTC, otakubeam commented on Contest_1/B.Palindrome.cpp
> +                str[i+palindrome_count] == str[position_left]) {
Посмотрел свой другой код. Когда как пишу. Здесь исправлю на пробелы

2020-10-01 14:32 UTC, otakubeam commented on Contest_1/B.Palindrome.cpp
> +            int expr1 = left_bound + right_bound - i + is_odd(!odd);
Исправил

2020-10-01 14:33 UTC, otakubeam commented on Contest_1/B.Palindrome.cpp
> +            int64 expr2 = static_cast<int64>(right_bound - i + 1);
Согласен. Исправил

2020-10-01 15:07 UTC, merged